### ISSUE TITLE
SSH hangs after authenticated

### ISSUE THREAD

**Issue by tttbone8122** [josephmachado/bitcoinMonitor#5]
From the Makefile (cloud-metabase) I removed the below part `open http://localhost:3001` because It was giving me the following error:  `/bin/bash: open: command not found`
```
cloud-metabase:
	terraform -chdir=./terraform output -raw private_key > private_key.pem && chmod 600 private_key.pem && ssh -o "IdentitiesOnly yes" -i private_key.pem ubuntu@$$(terraform -chdir=./terraform output -raw ec2_public_dns) -N -v -v -f -L 3001:$$(terraform -chdir=./terraform output -raw ec2_public_dns):3000 && rm private_key.pem
```
Also, ssh tunnel refusing connections with "channel 2" so I added  `-v -v` [as in this thread](https://serverfault.com/questions/489192/ssh-tunnel-refusing-connections-with-channel-2-open-failed)

After running the `make cloud-metabase` command, I get the following message:

```
OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolving "ec2-18-205-163-192.compute-1.amazonaws.com" port 22
debug2: ssh_connect_direct
debug1: Connecting to ec2-xx.xxx.xxx.xxx.compute-1.amazonaws.com [xx.xxx.xxx.xxx] port 22.
debug1: Connection established.
debug1: identity file private_key.pem type -1
debug1: identity file private_key.pem-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.9p1 Ubuntu-3
debug1: match: OpenSSH_8.9p1 Ubuntu-3 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to ec2-xx.xxx.xxx.xxx.compute-1.amazonaws.com:22 as 'ubuntu'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,sk-ssh-ed25519@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:G8FDUPgMnfKFC27I4q5bnyvEEVwHqfDfe26uONkarNQ
The authenticity of host 'ec2-1xx.xxx.xxx.xxx.compute-1.amazonaws.com (xx.xxx.xxx.xxx)' can't be established.
ECDSA key fingerprint is SHA256:G8FDUPgMnfKFC27I4q5bnyvEEVwHqfDfe26uONkarNQ.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'ec2-xx.xxx.xxx.xxx.compute-1.amazonaws.com,xx.xxx.xxx.xxx' (ECDSA) to the list of known hosts.
debug2: set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: private_key.pem  explicit
debug2: pubkey_prepare: done
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
debug1: kex_input_ext_info: publickey-hostbound@openssh.com (unrecognised)
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: private_key.pem
debug2: we sent a publickey packet, wait for reply
debug1: Authentication succeeded (publickey).
Authenticated to ec2-xx.xxx.xxx.xxx.compute-1.amazonaws.com ([xx.xxx.xxx.xxx]:22).
debug1: Local connections to LOCALHOST:3001 forwarded to remote address ec2-xx.xxx.xxx.xxx.compute-1.amazonaws.com:3000
debug1: Local forwarding listening on ::1 port 3001.
debug2: fd 4 setting O_NONBLOCK
debug1: channel 0: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 3001.
debug2: fd 5 setting O_NONBLOCK
debug1: channel 1: new [port listener]
debug2: fd 3 setting TCP_NODELAY
debug1: Requesting no-more-sessions@openssh.com
debug1: forking to background
debug1: Entering interactive session.
debug1: pledge: network
root@user:/home/user1/BitcoinMonitor# debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Remote: /home/ubuntu/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
root@user:/home/user1/BitcoinMonitor#
```

**Comment by josephmachado** [comment]
@tttbone8122 Hmm I can't seem to replicate this issue on my end. Do you mind just using the `ec2_public_dns` to open up metabase. You can do `http://your_ec2_public_dns:3000` to see the cloud Metabase UI. 

Are you running via WSL on windows?

**Comment by tttbone8122** [comment]
I'm using `Ubuntu 20.04` 

when I try to open `http://my_ec2_public_dns:3000`, I get the message **This site can't be reached. Took too long to respond...**


    cloud-metabase:
    	terraform -chdir=./terraform output -raw private_key > private_key.pem && chmod 600 private_key.pem && ssh -o "IdentitiesOnly yes" -i private_key.pem ubuntu@$$(terraform -chdir=./terraform output -raw ec2_public_dns) -N -v -f -L 3001:$$(terraform -chdir=./terraform output -raw ec2_public_dns):3000 && rm private_key.pem


I should see the cloud Metabase UI on: `http://my_ec2_public_dns:3000`


Below is part of the output I got after running this command. Everything looks fine here.The port has been forwarded 

    debug1: Authentications that can continue: publickey
    debug1: Next authentication method: publickey
    debug1: Trying private key: private_key.pem
    debug2: we sent a publickey packet, wait for reply
    debug1: Authentication succeeded (publickey).
    Authenticated to ec2-xx.xxx.xxx.xxx.compute-1.amazonaws.com ([xx.xxx.xxx.xxx]:22).
    debug1: Local connections to LOCALHOST:3001 forwarded to remote address ec2-xx.xxx.xxx.xxx.compute-1.amazonaws.com:3000


I went to the associated security group of the instance and allow both HTTP and HTTPS rules in the inbound-rules list. 




`lsof -i :3000`:

    COMMAND   PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
    chrome  15392 user   48u  IPv4 3933486      0t0  TCP user:42624->my_ec2_public_dns:3000 (SYN_SENT)
    chrome  15392 user   55u  IPv4 3933487      0t0  TCP user:42628->my_ec2_public_dns:3000 (SYN_SENT)
    chrome  15392 user   60u  IPv4 3933488      0t0  TCP user:42640->my_ec2_public_dns:3000 (SYN_SENT)


`lsof -i :3001`:

    COMMAND    PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
    chrome   15392 user   48u  IPv4 3952406      0t0  TCP user:45934->my_ec2_public_dns:3001 (SYN_SENT)
    chrome   15392 user   58u  IPv4 3952407      0t0  TCP user:45946->my_ec2_public_dns:3001 (SYN_SENT)
    chrome   15392 user   62u  IPv4 3952409      0t0  TCP user:45960->my_ec2_public_dns:3001 (SYN_SENT)
    ssh     758469   root    4u  IPv6 3915784      0t0  TCP ip6-localhost:3001 (LISTEN)
    ssh     758469   root    5u  IPv4 3915785      0t0  TCP localhost:3001 (LISTEN)

`ufw status` is **inactive**


**SYS_SENT**

"When you see a socket with this state, it is very likely that it has a problem with the Firewall (in this case block a port), although this state always happens, but should not last longer than a second (depending on the state of the network), but if it is maintained, there is a problem."
  
`http://my_ec2_public_dns:3000` keeps loading with `SYS_SENT` status and after a few minutes I get the message: **This site can't be reached**

**Comment by maciejbrasewicz** [comment]
I don't know whether to look for the problem on the aws side or somewhere else

**Comment by tttbone8122** [comment]
I don't know whether to look for the problem on the aws side or somewhere else

**Comment by josephmachado** [comment]
Hmm, I'd recommend checking 
1. That the containers in your EC2 is running. You can ssh into your EC2 instance with `make ssh-ec2` or if that does not work [try this](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html#AccessingInstancesLinuxSSHClient) and in your container run `docker ps` to see if Metabase is running, with the appropriate port?
2. Terraform might be pointing to older DNS in some cases. Can you check if the terraform's output (with `make infra-config`) are the same as your public DNS via AWS UI.

**Comment by tttbone8122** [comment]
I don't know why, but the first time the containers didn't create properly. Thank you!
